// Code generated by "stringer -type=SubRangeState"; DO NOT EDIT.

package subrange

import "fmt"

const _SubRangeState_name = "SR_NanSR_NormalSR_UnderSR_OverSR_WrapedUnderSR_WrapedOver"

var _SubRangeState_index = [...]uint8{0, 6, 15, 23, 30, 44, 57}

func (i SubRangeState) String() string {
	if i >= SubRangeState(len(_SubRangeState_index)-1) {
		return fmt.Sprintf("SubRangeState(%d)", i)
	}
	return _SubRangeState_name[_SubRangeState_index[i]:_SubRangeState_index[i+1]]
}
